// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: internal/proto/netem.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	StatusCode_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0}
}

type IfState int32

const (
	IfState_UP   IfState = 0
	IfState_DOWN IfState = 1
)

// Enum value maps for IfState.
var (
	IfState_name = map[int32]string{
		0: "UP",
		1: "DOWN",
	}
	IfState_value = map[string]int32{
		"UP":   0,
		"DOWN": 1,
	}
)

func (x IfState) Enum() *IfState {
	p := new(IfState)
	*p = x
	return p
}

func (x IfState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IfState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[1].Descriptor()
}

func (IfState) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[1]
}

func (x IfState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IfState.Descriptor instead.
func (IfState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1}
}

type ConsoleCltMsg_Code int32

const (
	ConsoleCltMsg_INIT   ConsoleCltMsg_Code = 0
	ConsoleCltMsg_DATA   ConsoleCltMsg_Code = 1
	ConsoleCltMsg_RESIZE ConsoleCltMsg_Code = 2
	ConsoleCltMsg_CLOSE  ConsoleCltMsg_Code = 3
)

// Enum value maps for ConsoleCltMsg_Code.
var (
	ConsoleCltMsg_Code_name = map[int32]string{
		0: "INIT",
		1: "DATA",
		2: "RESIZE",
		3: "CLOSE",
	}
	ConsoleCltMsg_Code_value = map[string]int32{
		"INIT":   0,
		"DATA":   1,
		"RESIZE": 2,
		"CLOSE":  3,
	}
)

func (x ConsoleCltMsg_Code) Enum() *ConsoleCltMsg_Code {
	p := new(ConsoleCltMsg_Code)
	*p = x
	return p
}

func (x ConsoleCltMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleCltMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[2].Descriptor()
}

func (ConsoleCltMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[2]
}

func (x ConsoleCltMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleCltMsg_Code.Descriptor instead.
func (ConsoleCltMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0, 0}
}

type ConsoleSrvMsg_Code int32

const (
	ConsoleSrvMsg_STDOUT ConsoleSrvMsg_Code = 0
	ConsoleSrvMsg_STDERR ConsoleSrvMsg_Code = 1
	ConsoleSrvMsg_ERROR  ConsoleSrvMsg_Code = 2
	ConsoleSrvMsg_CLOSE  ConsoleSrvMsg_Code = 3
)

// Enum value maps for ConsoleSrvMsg_Code.
var (
	ConsoleSrvMsg_Code_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "ERROR",
		3: "CLOSE",
	}
	ConsoleSrvMsg_Code_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"ERROR":  2,
		"CLOSE":  3,
	}
)

func (x ConsoleSrvMsg_Code) Enum() *ConsoleSrvMsg_Code {
	p := new(ConsoleSrvMsg_Code)
	*p = x
	return p
}

func (x ConsoleSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[3].Descriptor()
}

func (ConsoleSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[3]
}

func (x ConsoleSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleSrvMsg_Code.Descriptor instead.
func (ConsoleSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1, 0}
}

type PullSrvMsg_Code int32

const (
	PullSrvMsg_START PullSrvMsg_Code = 0
	PullSrvMsg_OK    PullSrvMsg_Code = 1
	PullSrvMsg_ERROR PullSrvMsg_Code = 2
)

// Enum value maps for PullSrvMsg_Code.
var (
	PullSrvMsg_Code_name = map[int32]string{
		0: "START",
		1: "OK",
		2: "ERROR",
	}
	PullSrvMsg_Code_value = map[string]int32{
		"START": 0,
		"OK":    1,
		"ERROR": 2,
	}
)

func (x PullSrvMsg_Code) Enum() *PullSrvMsg_Code {
	p := new(PullSrvMsg_Code)
	*p = x
	return p
}

func (x PullSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[4].Descriptor()
}

func (PullSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[4]
}

func (x PullSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullSrvMsg_Code.Descriptor instead.
func (PullSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{2, 0}
}

type CaptureSrvMsg_Code int32

const (
	CaptureSrvMsg_STDOUT CaptureSrvMsg_Code = 0
	CaptureSrvMsg_STDERR CaptureSrvMsg_Code = 1
	CaptureSrvMsg_OK     CaptureSrvMsg_Code = 2
	CaptureSrvMsg_ERROR  CaptureSrvMsg_Code = 3
)

// Enum value maps for CaptureSrvMsg_Code.
var (
	CaptureSrvMsg_Code_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "OK",
		3: "ERROR",
	}
	CaptureSrvMsg_Code_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"OK":     2,
		"ERROR":  3,
	}
)

func (x CaptureSrvMsg_Code) Enum() *CaptureSrvMsg_Code {
	p := new(CaptureSrvMsg_Code)
	*p = x
	return p
}

func (x CaptureSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptureSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[5].Descriptor()
}

func (CaptureSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[5]
}

func (x CaptureSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptureSrvMsg_Code.Descriptor instead.
func (CaptureSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{3, 0}
}

type ConsoleCltMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      ConsoleCltMsg_Code `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ConsoleCltMsg_Code" json:"code,omitempty"`
	PrjId     string             `protobuf:"bytes,2,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node      string             `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Shell     bool               `protobuf:"varint,4,opt,name=shell,proto3" json:"shell,omitempty"`
	TtyWidth  int32              `protobuf:"varint,5,opt,name=ttyWidth,proto3" json:"ttyWidth,omitempty"`
	TtyHeight int32              `protobuf:"varint,6,opt,name=ttyHeight,proto3" json:"ttyHeight,omitempty"`
	Data      []byte             `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConsoleCltMsg) Reset() {
	*x = ConsoleCltMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsoleCltMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCltMsg) ProtoMessage() {}

func (x *ConsoleCltMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCltMsg.ProtoReflect.Descriptor instead.
func (*ConsoleCltMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleCltMsg) GetCode() ConsoleCltMsg_Code {
	if x != nil {
		return x.Code
	}
	return ConsoleCltMsg_INIT
}

func (x *ConsoleCltMsg) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *ConsoleCltMsg) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ConsoleCltMsg) GetShell() bool {
	if x != nil {
		return x.Shell
	}
	return false
}

func (x *ConsoleCltMsg) GetTtyWidth() int32 {
	if x != nil {
		return x.TtyWidth
	}
	return 0
}

func (x *ConsoleCltMsg) GetTtyHeight() int32 {
	if x != nil {
		return x.TtyHeight
	}
	return 0
}

func (x *ConsoleCltMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConsoleSrvMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ConsoleSrvMsg_Code `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ConsoleSrvMsg_Code" json:"code,omitempty"`
	Data []byte             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConsoleSrvMsg) Reset() {
	*x = ConsoleSrvMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsoleSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleSrvMsg) ProtoMessage() {}

func (x *ConsoleSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleSrvMsg.ProtoReflect.Descriptor instead.
func (*ConsoleSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1}
}

func (x *ConsoleSrvMsg) GetCode() ConsoleSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return ConsoleSrvMsg_STDOUT
}

func (x *ConsoleSrvMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PullSrvMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  PullSrvMsg_Code `protobuf:"varint,1,opt,name=code,proto3,enum=netem.PullSrvMsg_Code" json:"code,omitempty"`
	Image string          `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Error string          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PullSrvMsg) Reset() {
	*x = PullSrvMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSrvMsg) ProtoMessage() {}

func (x *PullSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSrvMsg.ProtoReflect.Descriptor instead.
func (*PullSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{2}
}

func (x *PullSrvMsg) GetCode() PullSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return PullSrvMsg_START
}

func (x *PullSrvMsg) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PullSrvMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CaptureSrvMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code CaptureSrvMsg_Code `protobuf:"varint,1,opt,name=code,proto3,enum=netem.CaptureSrvMsg_Code" json:"code,omitempty"`
	Data []byte             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CaptureSrvMsg) Reset() {
	*x = CaptureSrvMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSrvMsg) ProtoMessage() {}

func (x *CaptureSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSrvMsg.ProtoReflect.Descriptor instead.
func (*CaptureSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureSrvMsg) GetCode() CaptureSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return CaptureSrvMsg_STDOUT
}

func (x *CaptureSrvMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodeIfStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrjId   string  `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node    string  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	IfIndex int32   `protobuf:"varint,3,opt,name=ifIndex,proto3" json:"ifIndex,omitempty"`
	State   IfState `protobuf:"varint,4,opt,name=state,proto3,enum=netem.IfState" json:"state,omitempty"`
}

func (x *NodeIfStateRequest) Reset() {
	*x = NodeIfStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeIfStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIfStateRequest) ProtoMessage() {}

func (x *NodeIfStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIfStateRequest.ProtoReflect.Descriptor instead.
func (*NodeIfStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{4}
}

func (x *NodeIfStateRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeIfStateRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeIfStateRequest) GetIfIndex() int32 {
	if x != nil {
		return x.IfIndex
	}
	return 0
}

func (x *NodeIfStateRequest) GetState() IfState {
	if x != nil {
		return x.State
	}
	return IfState_UP
}

type NodeInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrjId   string `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	IfIndex int32  `protobuf:"varint,3,opt,name=ifIndex,proto3" json:"ifIndex,omitempty"`
}

func (x *NodeInterfaceRequest) Reset() {
	*x = NodeInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInterfaceRequest) ProtoMessage() {}

func (x *NodeInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInterfaceRequest.ProtoReflect.Descriptor instead.
func (*NodeInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInterfaceRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeInterfaceRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeInterfaceRequest) GetIfIndex() int32 {
	if x != nil {
		return x.IfIndex
	}
	return 0
}

type NodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrjId string `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node  string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{6}
}

func (x *NodeRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WNetworkRequest) Reset() {
	*x = WNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WNetworkRequest) ProtoMessage() {}

func (x *WNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WNetworkRequest.ProtoReflect.Descriptor instead.
func (*WNetworkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{8}
}

func (x *WNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WNetworkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{9}
}

func (x *OpenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=netem.StatusCode" json:"code,omitempty"`
	Error string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{10}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_OK
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{11}
}

func (x *AckResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{12}
}

func (x *FileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version string  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{13}
}

func (x *VersionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name    string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id      string                       `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	OpenAt  string                       `protobuf:"bytes,4,opt,name=openAt,proto3" json:"openAt,omitempty"`
	Running bool                         `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	Nodes   []*StatusResponse_NodeStatus `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{14}
}

func (x *StatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetOpenAt() string {
	if x != nil {
		return x.OpenAt
	}
	return ""
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetNodes() []*StatusResponse_NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PrjListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *Status                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Projects []*PrjListResponse_Info `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
}

func (x *PrjListResponse) Reset() {
	*x = PrjListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrjListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjListResponse) ProtoMessage() {}

func (x *PrjListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjListResponse.ProtoReflect.Descriptor instead.
func (*PrjListResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{15}
}

func (x *PrjListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PrjListResponse) GetProjects() []*PrjListResponse_Info {
	if x != nil {
		return x.Projects
	}
	return nil
}

type PrjOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PrjOpenResponse) Reset() {
	*x = PrjOpenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrjOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjOpenResponse) ProtoMessage() {}

func (x *PrjOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjOpenResponse.ProtoReflect.Descriptor instead.
func (*PrjOpenResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{16}
}

func (x *PrjOpenResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PrjOpenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusResponse_IfStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State IfState `protobuf:"varint,2,opt,name=state,proto3,enum=netem.IfState" json:"state,omitempty"`
}

func (x *StatusResponse_IfStatus) Reset() {
	*x = StatusResponse_IfStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse_IfStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse_IfStatus) ProtoMessage() {}

func (x *StatusResponse_IfStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse_IfStatus.ProtoReflect.Descriptor instead.
func (*StatusResponse_IfStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{14, 0}
}

func (x *StatusResponse_IfStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse_IfStatus) GetState() IfState {
	if x != nil {
		return x.State
	}
	return IfState_UP
}

type StatusResponse_NodeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Running    bool                       `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Interfaces []*StatusResponse_IfStatus `protobuf:"bytes,10,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
}

func (x *StatusResponse_NodeStatus) Reset() {
	*x = StatusResponse_NodeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse_NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse_NodeStatus) ProtoMessage() {}

func (x *StatusResponse_NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse_NodeStatus.ProtoReflect.Descriptor instead.
func (*StatusResponse_NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{14, 1}
}

func (x *StatusResponse_NodeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse_NodeStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse_NodeStatus) GetInterfaces() []*StatusResponse_IfStatus {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type PrjListResponse_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpenAt string `protobuf:"bytes,3,opt,name=openAt,proto3" json:"openAt,omitempty"`
}

func (x *PrjListResponse_Info) Reset() {
	*x = PrjListResponse_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_netem_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrjListResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjListResponse_Info) ProtoMessage() {}

func (x *PrjListResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjListResponse_Info.ProtoReflect.Descriptor instead.
func (*PrjListResponse_Info) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{15, 0}
}

func (x *PrjListResponse_Info) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrjListResponse_Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrjListResponse_Info) GetOpenAt() string {
	if x != nil {
		return x.OpenAt
	}
	return ""
}

var File_internal_proto_netem_proto protoreflect.FileDescriptor

var file_internal_proto_netem_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x65,
	0x74, 0x65, 0x6d, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xff, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x43, 0x6c, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x43, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6a, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x6a, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x68, 0x65, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x74, 0x79, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x74, 0x79, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x74, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x74, 0x74, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x31, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x10, 0x03, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x53, 0x72,
	0x76, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x4f, 0x55, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x54, 0x44, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x03, 0x22, 0x8a, 0x01,
	0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x31, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x4f, 0x55,
	0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x03, 0x22, 0x7e, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6a, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6a, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6e, 0x65,
	0x74, 0x65, 0x6d, 0x2e, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x5a, 0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x6a, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6a, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x37,
	0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x6a, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72,
	0x6a, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0f, 0x57, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x35, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x34,
	0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x52, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x87, 0x03, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x36, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x44, 0x0a, 0x08, 0x49,
	0x66, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x1a, 0x7a, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a,
	0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x22, 0xb5, 0x01,
	0x0a, 0x0f, 0x50, 0x72, 0x6a, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6a, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x1a, 0x42, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x41, 0x74, 0x22, 0x48, 0x0a, 0x0f, 0x50, 0x72, 0x6a, 0x4f, 0x70, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a,
	0x1f, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x2a, 0x1b, 0x0a, 0x07, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x55,
	0x50, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x32, 0xae, 0x09,
	0x0a, 0x05, 0x4e, 0x65, 0x74, 0x65, 0x6d, 0x12, 0x3e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e,
	0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x16, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6a, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b,
	0x4f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x6e, 0x65,
	0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6a, 0x4f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x65,
	0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6e,
	0x65, 0x74, 0x65, 0x6d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x6e,
	0x65, 0x74, 0x65, 0x6d, 0x2e, 0x57, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x05, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x74,
	0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x15,
	0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0d, 0x43,
	0x61, 0x6e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x6e,
	0x65, 0x74, 0x65, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x12, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x43, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x6e,
	0x65, 0x74, 0x65, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x12,
	0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e,
	0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0a, 0x53, 0x65, 0x74, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6e, 0x65,
	0x74, 0x65, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x41,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x6f,
	0x79, 0x33, 0x31, 0x2f, 0x67, 0x6f, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_netem_proto_rawDescOnce sync.Once
	file_internal_proto_netem_proto_rawDescData = file_internal_proto_netem_proto_rawDesc
)

func file_internal_proto_netem_proto_rawDescGZIP() []byte {
	file_internal_proto_netem_proto_rawDescOnce.Do(func() {
		file_internal_proto_netem_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_netem_proto_rawDescData)
	})
	return file_internal_proto_netem_proto_rawDescData
}

var file_internal_proto_netem_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_internal_proto_netem_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_proto_netem_proto_goTypes = []interface{}{
	(StatusCode)(0),                   // 0: netem.StatusCode
	(IfState)(0),                      // 1: netem.IfState
	(ConsoleCltMsg_Code)(0),           // 2: netem.ConsoleCltMsg.Code
	(ConsoleSrvMsg_Code)(0),           // 3: netem.ConsoleSrvMsg.Code
	(PullSrvMsg_Code)(0),              // 4: netem.PullSrvMsg.Code
	(CaptureSrvMsg_Code)(0),           // 5: netem.CaptureSrvMsg.Code
	(*ConsoleCltMsg)(nil),             // 6: netem.ConsoleCltMsg
	(*ConsoleSrvMsg)(nil),             // 7: netem.ConsoleSrvMsg
	(*PullSrvMsg)(nil),                // 8: netem.PullSrvMsg
	(*CaptureSrvMsg)(nil),             // 9: netem.CaptureSrvMsg
	(*NodeIfStateRequest)(nil),        // 10: netem.NodeIfStateRequest
	(*NodeInterfaceRequest)(nil),      // 11: netem.NodeInterfaceRequest
	(*NodeRequest)(nil),               // 12: netem.NodeRequest
	(*ProjectRequest)(nil),            // 13: netem.ProjectRequest
	(*WNetworkRequest)(nil),           // 14: netem.WNetworkRequest
	(*OpenRequest)(nil),               // 15: netem.OpenRequest
	(*Status)(nil),                    // 16: netem.Status
	(*AckResponse)(nil),               // 17: netem.AckResponse
	(*FileResponse)(nil),              // 18: netem.FileResponse
	(*VersionResponse)(nil),           // 19: netem.VersionResponse
	(*StatusResponse)(nil),            // 20: netem.StatusResponse
	(*PrjListResponse)(nil),           // 21: netem.PrjListResponse
	(*PrjOpenResponse)(nil),           // 22: netem.PrjOpenResponse
	(*StatusResponse_IfStatus)(nil),   // 23: netem.StatusResponse.IfStatus
	(*StatusResponse_NodeStatus)(nil), // 24: netem.StatusResponse.NodeStatus
	(*PrjListResponse_Info)(nil),      // 25: netem.PrjListResponse.Info
	(*empty.Empty)(nil),               // 26: google.protobuf.Empty
}
var file_internal_proto_netem_proto_depIdxs = []int32{
	2,  // 0: netem.ConsoleCltMsg.code:type_name -> netem.ConsoleCltMsg.Code
	3,  // 1: netem.ConsoleSrvMsg.code:type_name -> netem.ConsoleSrvMsg.Code
	4,  // 2: netem.PullSrvMsg.code:type_name -> netem.PullSrvMsg.Code
	5,  // 3: netem.CaptureSrvMsg.code:type_name -> netem.CaptureSrvMsg.Code
	1,  // 4: netem.NodeIfStateRequest.state:type_name -> netem.IfState
	0,  // 5: netem.Status.code:type_name -> netem.StatusCode
	16, // 6: netem.AckResponse.status:type_name -> netem.Status
	16, // 7: netem.FileResponse.status:type_name -> netem.Status
	16, // 8: netem.VersionResponse.status:type_name -> netem.Status
	16, // 9: netem.StatusResponse.status:type_name -> netem.Status
	24, // 10: netem.StatusResponse.nodes:type_name -> netem.StatusResponse.NodeStatus
	16, // 11: netem.PrjListResponse.status:type_name -> netem.Status
	25, // 12: netem.PrjListResponse.projects:type_name -> netem.PrjListResponse.Info
	16, // 13: netem.PrjOpenResponse.status:type_name -> netem.Status
	1,  // 14: netem.StatusResponse.IfStatus.state:type_name -> netem.IfState
	23, // 15: netem.StatusResponse.NodeStatus.interfaces:type_name -> netem.StatusResponse.IfStatus
	26, // 16: netem.Netem.GetVersion:input_type -> google.protobuf.Empty
	26, // 17: netem.Netem.PullImages:input_type -> google.protobuf.Empty
	26, // 18: netem.Netem.Clean:input_type -> google.protobuf.Empty
	26, // 19: netem.Netem.GetProjects:input_type -> google.protobuf.Empty
	15, // 20: netem.Netem.OpenProject:input_type -> netem.OpenRequest
	13, // 21: netem.Netem.CloseProject:input_type -> netem.ProjectRequest
	13, // 22: netem.Netem.SaveProject:input_type -> netem.ProjectRequest
	13, // 23: netem.Netem.GetProjectStatus:input_type -> netem.ProjectRequest
	13, // 24: netem.Netem.ReadNetworkFile:input_type -> netem.ProjectRequest
	14, // 25: netem.Netem.WriteNetworkFile:input_type -> netem.WNetworkRequest
	13, // 26: netem.Netem.Check:input_type -> netem.ProjectRequest
	13, // 27: netem.Netem.Reload:input_type -> netem.ProjectRequest
	13, // 28: netem.Netem.Run:input_type -> netem.ProjectRequest
	12, // 29: netem.Netem.CanRunConsole:input_type -> netem.NodeRequest
	6,  // 30: netem.Netem.Console:input_type -> netem.ConsoleCltMsg
	12, // 31: netem.Netem.Start:input_type -> netem.NodeRequest
	12, // 32: netem.Netem.Stop:input_type -> netem.NodeRequest
	12, // 33: netem.Netem.Restart:input_type -> netem.NodeRequest
	10, // 34: netem.Netem.SetIfState:input_type -> netem.NodeIfStateRequest
	11, // 35: netem.Netem.Capture:input_type -> netem.NodeInterfaceRequest
	19, // 36: netem.Netem.GetVersion:output_type -> netem.VersionResponse
	8,  // 37: netem.Netem.PullImages:output_type -> netem.PullSrvMsg
	17, // 38: netem.Netem.Clean:output_type -> netem.AckResponse
	21, // 39: netem.Netem.GetProjects:output_type -> netem.PrjListResponse
	22, // 40: netem.Netem.OpenProject:output_type -> netem.PrjOpenResponse
	17, // 41: netem.Netem.CloseProject:output_type -> netem.AckResponse
	18, // 42: netem.Netem.SaveProject:output_type -> netem.FileResponse
	20, // 43: netem.Netem.GetProjectStatus:output_type -> netem.StatusResponse
	18, // 44: netem.Netem.ReadNetworkFile:output_type -> netem.FileResponse
	17, // 45: netem.Netem.WriteNetworkFile:output_type -> netem.AckResponse
	17, // 46: netem.Netem.Check:output_type -> netem.AckResponse
	17, // 47: netem.Netem.Reload:output_type -> netem.AckResponse
	17, // 48: netem.Netem.Run:output_type -> netem.AckResponse
	17, // 49: netem.Netem.CanRunConsole:output_type -> netem.AckResponse
	7,  // 50: netem.Netem.Console:output_type -> netem.ConsoleSrvMsg
	17, // 51: netem.Netem.Start:output_type -> netem.AckResponse
	17, // 52: netem.Netem.Stop:output_type -> netem.AckResponse
	17, // 53: netem.Netem.Restart:output_type -> netem.AckResponse
	17, // 54: netem.Netem.SetIfState:output_type -> netem.AckResponse
	9,  // 55: netem.Netem.Capture:output_type -> netem.CaptureSrvMsg
	36, // [36:56] is the sub-list for method output_type
	16, // [16:36] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_proto_netem_proto_init() }
func file_internal_proto_netem_proto_init() {
	if File_internal_proto_netem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_netem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsoleCltMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsoleSrvMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullSrvMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureSrvMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeIfStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrjListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrjOpenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse_IfStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse_NodeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_netem_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrjListResponse_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_netem_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_netem_proto_goTypes,
		DependencyIndexes: file_internal_proto_netem_proto_depIdxs,
		EnumInfos:         file_internal_proto_netem_proto_enumTypes,
		MessageInfos:      file_internal_proto_netem_proto_msgTypes,
	}.Build()
	File_internal_proto_netem_proto = out.File
	file_internal_proto_netem_proto_rawDesc = nil
	file_internal_proto_netem_proto_goTypes = nil
	file_internal_proto_netem_proto_depIdxs = nil
}
