listen: "localhost:10110"
tls:
  enabled: false
  ca: ""
  cert: ""
  key: ""
workdir: /tmp
docker:
  images:
    server: mroy31/gonetem-server
    host: mroy31/gonetem-host
    router: mroy31/gonetem-frr
    ovs: mroy31/gonetem-ovs
